### ISSUE TITLE
Demo website down

### ISSUE THREAD

**Issue by Davilarek** [bunnytrack/UTPackage.js#3]
Hi there, thanks for this awesome project.
Demo website mentioned in readme is no longer working. It would be cool if you could update it/publish the source code.

**Comment by sapphire-bt** [comment]
Hiya. You're welcome.

Just to confirm, are we talking about https://bunnytrack.net/package-explorer?

And when you say "no longer working", do you mean it doesn't load at all//404s or is there some kind of error when you try to load a file?

If the former, it seems to be online for me (try https://downforeveryoneorjustme.com/bunnytrack.net?proto=https); if the latter, perhaps the file you're trying to load was made with a newer (and unsupported) Unreal Engine version.

**Comment by Davilarek** [comment]
Huh, weird, yesterday I swear it timed out on my pc, but now it works...
I meant that the page just loaded infinitely.
When I get on my pc I will check again and close this issue (perhaps something was blocking that domain), sorry

EDIT: I just checked, "Connection Timed Out"

**Comment by sapphire-bt** [comment]
Hm, strange. Have you ever played on the BunnyTrack.net servers? There's a chance your IP address may have been caught in a ban.

Feel free to message me your IP and I can take a look (annoyingly GitHub doesn't have a private message feature but if you're on Discord you can find me there - https://discord.gg/ACppaYk).

In the meantime I'll add the demo page's source code like you suggested. The only reason I didn't do that years ago is because it's veeerry messy.

**Comment by Davilarek** [comment]
> Hm, strange. Have you ever played on the BunnyTrack.net servers?

I don't think so

**Comment by sapphire-bt** [comment]
Issue resolved - IP was caught in a wide ranging ban.

Demo page source added in this [commit](https://github.com/bunnytrack/UTPackage.js/commit/3c1a5f12c1f06ed466ea440104a62a47218123eb).
